<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLx3T7mU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLx3T7mU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLx3T7mU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLx3T7mU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLx3T7mU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Lx3T7mU',
    'container.build_id' => 'e557fdfa',
    'container.build_time' => 1606778932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLx3T7mU');
