<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2RlxK6X\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2RlxK6X/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2RlxK6X.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2RlxK6X\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2RlxK6X\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2RlxK6X',
    'container.build_id' => '293b87e6',
    'container.build_time' => 1606867114,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2RlxK6X');
